insert into authors (id, first_name, last_name) values (1, 'Kasey', 'Batch');
insert into authors (id, first_name, last_name) values (2, 'Harlie', 'Forsey');
insert into authors (id, first_name, last_name) values (3, 'Gates', 'Grafom');
insert into authors (id, first_name, last_name) values (4, 'Temple', 'Ambrosoni');
insert into authors (id, first_name, last_name) values (5, 'Francklin', 'Springett');
insert into authors (id, first_name, last_name) values (6, 'Cordey', 'Lovstrom');
insert into authors (id, first_name, last_name) values (7, 'Toddie', 'Angood');
insert into authors (id, first_name, last_name) values (8, 'Shay', 'Segebrecht');
insert into authors (id, first_name, last_name) values (9, 'Felipe', 'De La Haye');
insert into authors (id, first_name, last_name) values (10, 'Charlotta', 'Bluschke');
insert into authors (id, first_name, last_name) values (11, 'Sandor', 'Extall');
insert into authors (id, first_name, last_name) values (12, 'Vernor', 'Descroix');
insert into authors (id, first_name, last_name) values (13, 'Velma', 'Probat');
insert into authors (id, first_name, last_name) values (14, 'Gabriel', 'Dunphy');
insert into authors (id, first_name, last_name) values (15, 'Sada', 'Breede');
insert into authors (id, first_name, last_name) values (16, 'Clem', 'Eilhersen');
insert into authors (id, first_name, last_name) values (17, 'Ryann', 'Summerhayes');
insert into authors (id, first_name, last_name) values (18, 'Ken', 'Lithgow');
insert into authors (id, first_name, last_name) values (19, 'Eveline', 'Rutter');
insert into authors (id, first_name, last_name) values (20, 'Elvira', 'Krolak');
insert into authors (id, first_name, last_name) values (21, 'Ron', 'Tweede');

insert into books (id, price, price_old, title, author_id) values (1, 1998, 2961, 'Cheese - Montery Jack', 17);
insert into books (id, price, price_old, title, author_id) values (2, 2031, 3768, 'Swordfish Loin Portions', 13);
insert into books (id, price, price_old, title, author_id) values (3, 954, 1412, 'Bread - Kimel Stick Poly', 16);
insert into books (id, price, price_old, title, author_id) values (4, 2367, 1619, 'Otomegusa Dashi Konbu', 8);
insert into books (id, price, price_old, title, author_id) values (5, 1334, 2663, 'Bread Foccacia Whole', 16);
insert into books (id, price, price_old, title, author_id) values (6, 1657, 3222, 'Napkin Colour', 18);
insert into books (id, price, price_old, title, author_id) values (7, 2074, 1689, 'Muffin Mix - Morning Glory', 17);
insert into books (id, price, price_old, title, author_id) values (8, 1749, 1991, 'Pectin', 18);
insert into books (id, price, price_old, title, author_id) values (9, 923, 1872, 'Nantucket Orange Juice', 19);
insert into books (id, price, price_old, title, author_id) values (10, 1788, 1876, 'Nantucket - Pomegranate Pear', 17);
insert into books (id, price, price_old, title, author_id) values (11, 2372, 2668, 'Whmis - Spray Bottle Trigger', 11);
insert into books (id, price, price_old, title, author_id) values (12, 2781, 1820, 'Salmon Steak - Cohoe 6 Oz', 19);
insert into books (id, price, price_old, title, author_id) values (13, 2750, 2597, 'Cheese - Mozzarella, Shredded', 11);
insert into books (id, price, price_old, title, author_id) values (14, 1720, 2252, 'Compound - Strawberry', 7);
insert into books (id, price, price_old, title, author_id) values (15, 2675, 2170, 'Cloves - Ground', 1);
insert into books (id, price, price_old, title, author_id) values (16, 2210, 3767, 'Ham - Cooked Italian', 1);
insert into books (id, price, price_old, title, author_id) values (17, 1536, 2749, 'Vermacelli - Sprinkles, Assorted', 10);
insert into books (id, price, price_old, title, author_id) values (18, 2762, 3634, 'Juice - Tomato, 48 Oz', 9);
insert into books (id, price, price_old, title, author_id) values (19, 2586, 1356, 'Calvados - Boulard', 19);
insert into books (id, price, price_old, title, author_id) values (20, 1038, 1989, 'Tomatoes - Roma', 21);
insert into books (id, price, price_old, title, author_id) values (21, 1275, 2215, 'Onions - Spanish', 15);
