package com.example.MyBookShopApp.data.book;

import com.example.MyBookShopApp.data.author.Author;
import com.example.MyBookShopApp.data.book.file.FileDownloadEntity;
import com.example.MyBookShopApp.data.book.review.BookReviewEntity;
import com.example.MyBookShopApp.data.genre.GenreEntity;
import com.example.MyBookShopApp.data.payments.BalanceTransactionEntity;
import com.example.MyBookShopApp.data.tag.TagEntity;
import com.example.MyBookShopApp.data.user.UserEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Entity
@Table(name = "book")
@ApiModel(description = "entity representing a book")
@JsonIgnoreProperties({"author", "users", "genre", "fileDownload", "balanceTransaction", "bookReview"})
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private Integer id;

    @Column(columnDefinition = "TEXT NOT NULL")
    @ApiModelProperty("book description text")
    private String description;

    @Column(columnDefinition = "SMALLINT NOT NULL")
    @ApiModelProperty("book price without discount")
    private short discount;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("image url")
    private String image;

    @Column(name = "is_bestseller", columnDefinition = "SMALLINT NOT NULL")
    @ApiModelProperty("if isBestseller = 1 so the book is considered to be bestseller and  if 0 the book is not a " +
            "bestseller")
    private short isBestseller;

    @Column(columnDefinition = "INT NOT NULL")
    @ApiModelProperty("book price without discount")
    private int price;

    @Column(name = "pub_date", columnDefinition = "DATE NOT NULL")
    @Temporal(TemporalType.DATE)
    @ApiModelProperty("date of book publication")
    private Date pubDate;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("mnemonical identity sequence of characters")
    private String slug;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("book title")
    private String title;

    @Column(name = "stat_in_cart", columnDefinition = "INT NOT NULL")
    private Integer statInCart;

    @Column(name = "stat_bought", columnDefinition = "INT NOT NULL")
    private Integer statBought;

    @Column(name = "stat_postponed", columnDefinition = "INT NOT NULL")
    private Integer statPostponed;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinTable(name = "book2author",
            joinColumns = {@JoinColumn(name = "bookId")},
            inverseJoinColumns = {@JoinColumn(name = "authorId")})
    private Author author;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinTable(name = "book2genre",
            joinColumns = {@JoinColumn(name = "bookId")},
            inverseJoinColumns = {@JoinColumn(name = "genreId")})
    private GenreEntity genre;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "book2user",
            joinColumns = {@JoinColumn(name = "bookId")},
            inverseJoinColumns = {@JoinColumn(name = "userId")})
    private List<UserEntity> users;

    @JsonIgnore
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "book2tag",
            joinColumns = @JoinColumn(name = "bookId"),
            inverseJoinColumns = @JoinColumn(name = "tagId"))
    private List<TagEntity> tags;

    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "bookId")
    private List<FileDownloadEntity> fileDownload;

    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "bookId")
    private List<BalanceTransactionEntity> balanceTransaction;

    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "bookId")
    private List<BookReviewEntity> bookReview;

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public GenreEntity getGenre() {
        return genre;
    }

    public void setGenre(GenreEntity genre) {
        this.genre = genre;
    }

    public List<UserEntity> getUsers() {
        return users;
    }

    public void setUsers(List<UserEntity> users) {
        this.users = users;
    }

    public List<FileDownloadEntity> getFileDownload() {
        return fileDownload;
    }

    public void setFileDownload(List<FileDownloadEntity> fileDownloadEntities) {
        this.fileDownload = fileDownloadEntities;
    }

    public List<BalanceTransactionEntity> getBalanceTransaction() {
        return balanceTransaction;
    }

    public void setBalanceTransaction(List<BalanceTransactionEntity> balanceTransaction) {
        this.balanceTransaction = balanceTransaction;
    }

    public List<BookReviewEntity> getBookReview() {
        return bookReview;
    }

    public void setBookReview(List<BookReviewEntity> bookReview) {
        this.bookReview = bookReview;
    }

    public Integer getStatInCart() {
        return statInCart;
    }

    public void setStatInCart(Integer statInCart) {
        this.statInCart = statInCart;
    }

    public Integer getStatBought() {
        return statBought;
    }

    public void setStatBought(Integer statBought) {
        this.statBought = statBought;
    }

    public Integer getStatPostponed() {
        return statPostponed;
    }

    public void setStatPostponed(Integer statPostponed) {
        this.statPostponed = statPostponed;
    }

    public List<TagEntity> getTags() {
        return tags;
    }

    public void setTags(List<TagEntity> tags) {
        this.tags = tags;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public short getDiscount() {
        return discount;
    }

    public void setDiscount(short discount) {
        this.discount = discount;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public short getIsBestseller() {
        return isBestseller;
    }

    public void setIsBestseller(short isBestseller) {
        this.isBestseller = isBestseller;
    }

    public Date getPubDate() {
        return pubDate;
    }

    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", author=" + author +
                ", title='" + title + '\'' +
                ", price=" + price +
                '}';
    }
}
